services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: golf_club_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3abuSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/golf_club_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3abuSQL